#ifndef DATA_PUBLISHER_H
#define DATA_PUBLISHER_H

#include <string>
#include <vector>

// Simplified DDS types for demonstration
// In real implementation, these would be generated by RTI Connext
struct RoboticsData {
    long timestamp;
    std::vector<double> joint_positions;
    std::vector<double> joint_velocities;
    std::vector<double> force_readings;
    std::string safety_status;
    double collision_risk;
    bool emergency_stop_engaged;
    std::string procedure_phase;
    double procedure_duration;
};

struct EmergencyCommand {
    long timestamp;
    std::string command_type;
    std::string reason;
    std::string severity;
    bool requires_acknowledgment;
};

struct SafetyAlert {
    std::string alert_id;
    long timestamp;
    std::string severity;
    std::string message;
    std::string component;
    std::string recommended_action;
};

struct SafetyMetrics {
    std::vector<double> joint_positions;
    std::vector<double> joint_velocities;
    std::vector<double> force_readings;
    std::string safety_status;
    double collision_risk;
    bool emergency_stop;
    std::string procedure_phase;
    double procedure_duration;
    double safety_score;
};

class RoboticsDataPublisher {
public:
    RoboticsDataPublisher();
    void publishSafetyData(const SafetyMetrics& metrics);
    void publishEmergencyStop(const std::string& reason);
    void publishSafetyAlert(const SafetyAlert& alert);
};

#endif // DATA_PUBLISHER_H
